"""
scripts/generate_baseline_report.py

S2 W7~W8 R3 산출물 — Baseline 평가 리포트 생성 스크립트.
S2 W7~W8 R3 deliverable — Baseline evaluation report generation script.

성능 수치 / Performance metrics:
    run_baseline.py 가 생성한 baseline_summary.json 에서 로드 (Test셋 공식 수치).
    Loaded from baseline_summary.json (official Test-set metrics by run_baseline.py).

시각화 차트 / Visualization charts:
    전체 데이터 추론 결과 사용 (Confusion Matrix, MAE Heatmap 등).
    Uses full-dataset inference for visualization charts.

실행 방법 / How to run:
    python src/scripts/generate_baseline_report.py
    python src/scripts/generate_baseline_report.py --channels C K
    python src/scripts/generate_baseline_report.py --open-browser

전제 조건 / Prerequisites:
    - run_baseline.py 실행 완료
      -> data_set/baseline/best_{channel}.pt
      -> data_set/baseline/baseline_summary.json
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

from evaluation.confusion import plot_confusion_matrix
from evaluation.evaluator import Evaluator
from evaluation.metrics import (
    NUM_LEVELS,
    TARGET_MAE,
    TARGET_OVERALL_ACC,
    TARGET_PER_CLASS_F1,
    TARGET_PER_COLOR_ACC,
    check_targets,
    compute_all_channels,
)
from src.utils import (
    build_model,
    create_directories,
    get_logger,
    get_nested,
    load_config,
    setup_logging,
    validate_config,
)


def load_baseline_summary(baseline_dir: Path) -> dict:
    """
    run_baseline.py 가 생성한 baseline_summary.json 을 로드한다.
    Loads baseline_summary.json generated by run_baseline.py.
    """
    summary_path = baseline_dir / "baseline_summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(
            f"baseline_summary.json not found: {summary_path}\n"
            "Run run_baseline.py first."
        )
    with open(summary_path, encoding="utf-8") as f:
        return json.load(f)


def summary_to_cards(summary: dict, available: list) -> dict:
    """
    baseline_summary.json 의 채널별 결과를 성능 카드 dict 로 변환한다.
    Test셋 기준 공식 수치 / Official Test-set metrics.
    """
    cards = {}
    valid = [
        r
        for r in summary["results"]
        if not r.get("skipped") and r["channel"] in available
    ]

    for r in valid:
        cards[r["channel"]] = {
            "test_acc": r["test_acc"],
            "mae": r["mae"],
            "best_val_acc": r["best_val_acc"],
            "n_train": r["n_train"],
            "n_val": r["n_val"],
            "n_test": r["n_test"],
            "pass_acc": r["pass_acc"],
            "pass_mae": r["pass_mae"],
        }

    if valid:
        cards["overall"] = {
            "test_acc": round(sum(r["test_acc"] for r in valid) / len(valid), 4),
            "mae": round(sum(r["mae"] for r in valid) / len(valid), 4),
        }

    return cards


def build_baseline_html(report_data: dict, output_path: Path) -> None:
    """단일 통합 HTML 리포트를 생성한다 (PRD 8.2.3)."""
    import plotly.io as pio

    meta = report_data["meta"]
    cards = report_data["cards"]
    metrics = report_data["metrics"]
    figs = report_data["figures"]
    phase3 = report_data["phase3_text"]
    df_miss = report_data["misclassified"]

    def fig_div(fig, div_id):
        return pio.to_html(fig, full_html=False, include_plotlyjs=False, div_id=div_id)

    def badge(passed):
        cls, txt = ("pass", "PASS") if passed else ("fail", "FAIL")
        return f'<span class="badge {cls}">{txt}</span>'

    # 성능 카드 테이블 (baseline_summary.json — Test셋 공식 수치)
    color_rows = ""
    for ch in ["Y", "M", "C", "K"]:
        if ch not in cards:
            continue
        c = cards[ch]
        color_rows += f"""
        <tr>
            <td><span class="ch-badge ch-{ch}">{ch}</span></td>
            <td>{c['test_acc']:.4f} {badge(c['pass_acc'])}</td>
            <td>{c['mae']:.4f} {badge(c['pass_mae'])}</td>
            <td>{c['best_val_acc']:.4f}</td>
            <td>{c['n_train']}</td>
            <td>{c['n_val']}</td>
            <td>{c['n_test']}</td>
        </tr>"""

    # Per-class 테이블 (전체 추론 기반)
    pc_rows = ""
    for pc in metrics.get("overall", {}).get("per_class", []):
        pc_rows += f"""
        <tr>
            <td>Level {pc['level']}</td>
            <td>{pc['precision']:.4f}</td>
            <td>{pc['recall']:.4f}</td>
            <td>{pc['f1']:.4f} {badge(pc['f1'] >= TARGET_PER_CLASS_F1)}</td>
        </tr>"""

    # 오분류 샘플 테이블
    miss_rows = ""
    if len(df_miss) > 0:
        for _, row in df_miss.head(20).iterrows():
            gc = "gap-high" if row["error_gap"] >= 2 else "gap-low"
            miss_rows += f"""
            <tr>
                <td>{row['filename']}</td>
                <td><span class="ch-badge ch-{row['color']}">{row['color']}</span></td>
                <td>{row['true_level']}</td><td>{row['pred_level']}</td>
                <td class="{gc}">{row['error_gap']}</td>
                <td>{row['confidence']:.4f}</td>
            </tr>"""
        if len(df_miss) > 20:
            miss_rows += f'<tr><td colspan="6" class="more-row">... {len(df_miss)-20} more rows</td></tr>'
    else:
        miss_rows = (
            '<tr><td colspan="6" class="no-miss">No misclassified samples</td></tr>'
        )

    phase3_html = phase3.replace("\n", "<br>").replace(
        "TERMINATE", "<strong>TERMINATE</strong>"
    )

    overall = cards.get("overall", {})
    avg_acc = overall.get("test_acc", 0)
    avg_mae = overall.get("mae", 0)
    n_total = sum(cards[c]["n_test"] for c in ["Y", "M", "C", "K"] if c in cards)
    acc_cls = "pass-card" if avg_acc >= TARGET_OVERALL_ACC else "fail-card"
    mae_cls = "pass-card" if avg_mae <= TARGET_MAE else "fail-card"
    cm_divs = "\n".join(
        fig_div(figs[f"cm_{ch}"], f"fig-cm-{ch}")
        for ch in meta["channels"]
        if f"cm_{ch}" in figs
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Grayspot Baseline Report — {meta['experiment']}</title>
<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
<style>
:root{{--bg:#0b1220;--sf:#111927;--sf2:#172032;--bd:rgba(255,255,255,0.08);
--fg:#e6eef8;--fm:#9fb4c8;--c1:#66d9ff;--c2:#50e3c2;
--pass:#2ecc71;--fail:#e74c3c;--gh:#e74c3c;--gl:#f1c40f}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:'Segoe UI',sans-serif;background:var(--bg);color:var(--fg);
line-height:1.7;padding:2rem;max-width:1300px;margin:0 auto}}
.rh{{border-bottom:2px solid var(--c1);padding-bottom:1.2rem;margin-bottom:2rem}}
.rh h1{{font-size:1.9rem;color:var(--c1);margin-bottom:.3rem}}
.mg{{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));
gap:.4rem 2rem;margin-top:.8rem;font-size:.88rem;color:var(--fm)}}
.mg span{{color:var(--fg);font-weight:600}}
.nb{{background:rgba(102,217,255,.08);border:1px solid rgba(102,217,255,.3);
border-radius:6px;padding:.6rem 1rem;font-size:.82rem;color:var(--fm);margin-top:1rem}}
.sec{{background:var(--sf);border:1px solid var(--bd);border-radius:8px;
padding:1.5rem;margin-bottom:1.8rem}}
.st{{font-size:1.1rem;font-weight:700;color:var(--c2);border-left:4px solid var(--c2);
padding-left:.7rem;margin-bottom:1.2rem}}
.sn{{color:var(--fm);font-size:.82rem;margin-right:.5rem}}
.snote{{font-size:.78rem;color:var(--fm);margin-bottom:.8rem}}
table{{width:100%;border-collapse:collapse;font-size:.9rem}}
th,td{{border:1px solid var(--bd);padding:.5rem .8rem;text-align:left}}
th{{background:var(--sf2);color:var(--fm);font-weight:600}}
tr:hover{{background:rgba(255,255,255,.02)}}
.badge{{display:inline-block;padding:.1rem .45rem;border-radius:4px;
font-size:.75rem;font-weight:700;margin-left:.35rem;vertical-align:middle}}
.badge.pass{{background:rgba(46,204,113,.18);color:var(--pass);border:1px solid var(--pass)}}
.badge.fail{{background:rgba(231,76,60,.18);color:var(--fail);border:1px solid var(--fail)}}
.ch-badge{{display:inline-block;padding:.1rem .5rem;border-radius:4px;font-size:.82rem;font-weight:700}}
.ch-Y{{background:rgba(245,230,66,.15);color:#f5e642;border:1px solid #f5e64280}}
.ch-M{{background:rgba(233,30,140,.15);color:#e91e8c;border:1px solid #e91e8c80}}
.ch-C{{background:rgba(0,180,216,.15);color:#00b4d8;border:1px solid #00b4d880}}
.ch-K{{background:rgba(180,180,180,.15);color:#ccc;border:1px solid #cccccc80}}
.gap-high{{color:var(--gh);font-weight:700}}.gap-low{{color:var(--gl);font-weight:600}}
.no-miss{{text-align:center;color:var(--pass);padding:1rem}}
.more-row{{text-align:center;color:var(--fm);font-size:.85rem}}
.p3box{{background:rgba(124,58,237,.1);border:1px solid rgba(124,58,237,.4);
border-radius:6px;padding:1rem 1.2rem;font-size:.9rem;line-height:1.9}}
.p3box strong{{color:var(--pass);font-size:1rem}}
.ts{{display:flex;gap:1rem;flex-wrap:wrap;margin-bottom:1.2rem}}
.tc{{flex:1;min-width:180px;background:var(--sf2);border:1px solid var(--bd);
border-radius:6px;padding:.8rem 1rem}}
.tc .lbl{{font-size:.78rem;color:var(--fm)}}
.tc .val{{font-size:1.5rem;font-weight:700;margin:.1rem 0}}
.tc .sub{{font-size:.72rem;color:var(--fm);margin-top:2px}}
.tc .tgt{{font-size:.75rem;color:var(--fm)}}
.tc.pass-card .val{{color:var(--pass)}}.tc.fail-card .val{{color:var(--fail)}}
.cmg{{display:grid;grid-template-columns:repeat(auto-fill,minmax(480px,1fr));gap:1rem}}
hr{{border:none;border-top:1px solid var(--bd);margin:1.5rem 0}}
.rf{{text-align:center;color:var(--fm);font-size:.8rem;margin-top:2rem;
padding-top:1rem;border-top:1px solid var(--bd)}}
</style>
</head>
<body>

<div class="rh">
  <h1>Grayspot Baseline Evaluation Report</h1>
  <div class="mg">
    <div>Experiment: <span>{meta['experiment']}</span></div>
    <div>Generated: <span>{meta['generated_at']}</span></div>
    <div>Backbone: <span>{meta['backbone']}</span></div>
    <div>Epochs: <span>{meta['epochs']}</span></div>
    <div>Image Size: <span>{meta['image_size']}x{meta['image_size']}</span></div>
    <div>Channels: <span>{', '.join(meta['channels'])}</span></div>
    <div>Test Samples: <span>{n_total}</span></div>
    <div>Stage: <span>S2 W7~W8 Baseline (PRD 8.2.3)</span></div>
  </div>
  <div class="nb">
    <strong>Performance metrics</strong> (Section 1) are from
    <strong>baseline_summary.json</strong> — official Test-set results (Stratified 15%)
    computed by run_baseline.py.<br>
    Visualization charts (Sections 2~6) use full-dataset inference.
  </div>
</div>

<div class="sec">
  <div class="st"><span class="sn">1.</span>Performance Summary — Test-set Official</div>
  <div class="snote">Source: baseline_summary.json (Test-set 15% / run_baseline.py)</div>
  <div class="ts">
    <div class="tc {acc_cls}">
      <div class="lbl">Avg. Test Accuracy</div>
      <div class="val">{avg_acc:.1%}</div>
      <div class="sub">Average across channels</div>
      <div class="tgt">Target >= {TARGET_OVERALL_ACC:.0%}</div>
    </div>
    <div class="tc {mae_cls}">
      <div class="lbl">Avg. MAE</div>
      <div class="val">{avg_mae:.4f}</div>
      <div class="sub">Average across channels</div>
      <div class="tgt">Target <= {TARGET_MAE:.2f}</div>
    </div>
    <div class="tc pass-card">
      <div class="lbl">Test Samples</div>
      <div class="val">{n_total}</div>
      <div class="sub">Total across channels</div>
      <div class="tgt">Evaluated</div>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Channel</th>
        <th>Test Acc (target>={TARGET_PER_COLOR_ACC:.0%})</th>
        <th>MAE (target<={TARGET_MAE:.2f})</th>
        <th>Best Val Acc</th>
        <th>N Train</th><th>N Val</th><th>N Test</th>
      </tr>
    </thead>
    <tbody>{color_rows}</tbody>
  </table>
</div>

<div class="sec">
  <div class="st"><span class="sn">2.</span>Confusion Matrix (Row-Normalized)</div>
  <div class="snote">Source: full-dataset inference (visualization only)</div>
  <div class="cmg">{cm_divs}</div>
  <hr>{fig_div(figs['cm_overall'],'fig-cm-overall')}
</div>

<div class="sec">
  <div class="st"><span class="sn">3.</span>Per-Class Performance (Overall)</div>
  <div class="snote">Source: full-dataset inference (visualization only)</div>
  {fig_div(figs['per_class'],'fig-per-class')}
  <hr>
  <table>
    <thead>
      <tr><th>Level</th><th>Precision</th><th>Recall</th>
      <th>F1 (target>={TARGET_PER_CLASS_F1:.2f})</th></tr>
    </thead>
    <tbody>{pc_rows}</tbody>
  </table>
</div>

<div class="sec">
  <div class="st"><span class="sn">4.</span>MAE Heatmap (Color x True Level)</div>
  <div class="snote">Source: full-dataset inference (visualization only)</div>
  {fig_div(figs['mae'],'fig-mae')}
</div>

<div class="sec">
  <div class="st"><span class="sn">5.</span>Misclassified Samples (top 20)</div>
  <div class="snote">Source: full-dataset inference (visualization only)</div>
  {fig_div(figs['mismatch'],'fig-mismatch')}
  <hr>
  <table>
    <thead>
      <tr><th>Filename</th><th>Channel</th><th>True</th>
      <th>Pred</th><th>Gap</th><th>Confidence</th></tr>
    </thead>
    <tbody>{miss_rows}</tbody>
  </table>
</div>

<div class="sec">
  <div class="st"><span class="sn">6.</span>Confidence Distribution (PRD 14.2)</div>
  <div class="snote">Source: full-dataset inference (visualization only)</div>
  {fig_div(figs['conf_dist'],'fig-conf')}
</div>

<div class="sec">
  <div class="st"><span class="sn">7.</span>Phase 3 Feedback Decision (PRD 3.3.2)</div>
  <div class="p3box">{phase3_html}</div>
</div>

<div class="rf">
  Grayspot Detection Pipeline &middot; Stage 2 Baseline Report &middot; {meta['generated_at']}
</div>
</body>
</html>"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate baseline evaluation report")
    parser.add_argument("--channels", nargs="+", default=["Y", "M", "C", "K"])
    parser.add_argument("--open-browser", action="store_true")
    args = parser.parse_args()

    cfg = load_config()
    if not validate_config(cfg):
        print("[ERROR] Configuration validation failed.")
        sys.exit(1)

    create_directories(cfg)
    setup_logging(
        log_dir=Path(cfg["storage"]["logs_dir"]),
        level=get_nested(cfg, "logging.level") or "INFO",
        format_style=get_nested(cfg, "logging.format") or "detailed",
        console=get_nested(cfg, "logging.console_output"),
        file=get_nested(cfg, "logging.file_output"),
    )
    logger = get_logger(__name__)

    baseline_dir = Path(cfg["storage"]["data_root"]) / "baseline"
    labeled_dir = Path(cfg["storage"]["labeled_dir"])
    labels_csv = Path(cfg["storage"]["data_root"]) / "labels_v0.csv"
    output_dir = ROOT / "outputs" / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    device = torch.device(cfg["system"]["device"])

    logger.info("=" * 60)
    logger.info("Baseline Report Generation")
    logger.info(f"  Channels : {args.channels}")
    logger.info(f"  Device   : {device}")
    logger.info("=" * 60)

    # ── 1. baseline_summary.json 로드 (공식 Test-set 수치) ───────────────
    logger.info("Loading baseline_summary.json (official Test-set metrics)...")
    summary = load_baseline_summary(baseline_dir)
    available = [
        r["channel"]
        for r in summary["results"]
        if not r.get("skipped") and r["channel"] in args.channels
    ]

    if not available:
        logger.error("No valid results in baseline_summary.json.")
        sys.exit(1)

    cards = summary_to_cards(summary, available)
    logger.info(f"Channels from summary: {available}")
    for ch in available:
        c = cards[ch]
        logger.info(
            f'  [{ch}] Test Acc: {c["test_acc"]:.4f} {"[PASS]" if c["pass_acc"] else "[FAIL]"} | '
            f'MAE: {c["mae"]:.4f} {"[PASS]" if c["pass_mae"] else "[FAIL]"}'
        )

    # ── 2. 전체 데이터 추론 (차트용) ─────────────────────────────────────
    logger.info("Running full-dataset inference for visualization charts...")
    all_results: dict = {}

    for ch in available:
        ckpt = baseline_dir / f"best_{ch}.pt"
        if not ckpt.exists():
            logger.warning(f"[{ch}] Checkpoint not found: {ckpt} — skipping")
            continue

        model = build_model(cfg, ckpt, device)
        ev = Evaluator(
            model=model,
            labeled_dir=labeled_dir,
            labels_csv=labels_csv,
            output_dir=output_dir / "tmp",
            device=device,
            image_size=cfg["data"]["image_size"],
            batch_size=cfg["phase2"]["batch_size"],
            num_levels=cfg["data"]["num_levels"],
            cfg=cfg,
        )
        all_results.update(ev.run(channels=[ch]))
        logger.info(f"[{ch}] Inference done (visualization only)")

    # ── 3. 전체 추론 기반 지표 (차트용) ──────────────────────────────────
    metrics = compute_all_channels(
        all_results,
        list(all_results.keys()),
        num_classes=cfg["data"]["num_levels"],
    )

    # ── 4. 차트 생성 ──────────────────────────────────────────────────────
    logger.info("Building charts...")
    ev_report = Evaluator(
        model=build_model(cfg, baseline_dir / f"best_{available[0]}.pt", device),
        labeled_dir=labeled_dir,
        labels_csv=labels_csv,
        output_dir=output_dir,
        device=device,
        image_size=cfg["data"]["image_size"],
        batch_size=cfg["phase2"]["batch_size"],
        num_levels=cfg["data"]["num_levels"],
        cfg=cfg,
    )

    df_miss = ev_report.get_misclassified(all_results, list(all_results.keys()))
    figs: dict = {}
    figs["per_class"] = ev_report._build_per_class_chart(metrics)
    figs["mae"] = ev_report._build_mae_heatmap(all_results, list(all_results.keys()))
    figs["mismatch"] = ev_report._build_mismatch_scatter(df_miss)
    figs["conf_dist"] = ev_report._build_confidence_dist(
        all_results, list(all_results.keys())
    )

    all_true = np.concatenate([all_results[c]["y_true"] for c in all_results])
    all_pred = np.concatenate([all_results[c]["y_pred"] for c in all_results])

    for ch in all_results:
        yt, yp = all_results[ch]["y_true"], all_results[ch]["y_pred"]
        figs[f"cm_{ch}"] = plot_confusion_matrix(
            yt,
            yp,
            title=f'[{ch}] Confusion Matrix  Full-dataset Acc={metrics[ch]["accuracy"]:.4f}',
            normalize=True,
        )
    figs["cm_overall"] = plot_confusion_matrix(
        all_true,
        all_pred,
        title=f'[Overall] Confusion Matrix  Full-dataset Acc={metrics["overall"]["accuracy"]:.4f}',
        normalize=True,
    )

    # ── 5. Phase 3 판단 (baseline_summary.json 공식 수치 기반) ───────────
    lines = ["=== Phase 3 Feedback Decision (PRD 3.3.2) ==="]
    all_pass = all(cards[c]["pass_acc"] and cards[c]["pass_mae"] for c in available)

    if all_pass:
        lines.append("All targets met -- TERMINATE Swing")
    else:
        lines.append("Action required:")
        for ch in available:
            c = cards[ch]
            if not c["pass_acc"]:
                lines.append(
                    f'  [{ch}] Test Acc {c["test_acc"]:.3f} < {TARGET_PER_COLOR_ACC}'
                    " -> Phase 0 (retrain representation)"
                )
            if not c["pass_mae"]:
                lines.append(
                    f'  [{ch}] MAE {c["mae"]:.3f} > {TARGET_MAE}'
                    " -> Phase 0 (representation learning retry)"
                )

    lines += [
        "",
        f'  Avg. Test Accuracy : {cards["overall"]["test_acc"]:.4f}  (target >= {TARGET_PER_COLOR_ACC})',
        f'  Avg. MAE           : {cards["overall"]["mae"]:.4f}  (target <= {TARGET_MAE})',
        f"  Source             : baseline_summary.json (Test-set 15%)",
    ]
    phase3_text = "\n".join(lines)

    # ── 6. CSV / JSON 저장 ────────────────────────────────────────────────
    ev_report.save_csv(
        all_results, experiment_name="baseline", channels=list(all_results.keys())
    )
    ev_report.save_json(
        metrics,
        experiment_name="baseline",
        channels=list(all_results.keys()),
        checkpoint_path=", ".join(f"best_{ch}.pt" for ch in available),
    )
    miss_csv = output_dir / "misclassified_baseline.csv"
    df_miss.to_csv(miss_csv, index=False, encoding="utf-8-sig")
    logger.info(f"Saved: {miss_csv}")

    # ── 7. HTML 리포트 생성 ───────────────────────────────────────────────
    meta = {
        "experiment": "baseline",
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "backbone": summary.get("backbone", cfg["model"]["backbone"]),
        "epochs": summary.get("epochs", cfg["phase2"]["epochs"]),
        "image_size": cfg["data"]["image_size"],
        "channels": available,
    }

    baseline_html = output_dir / "baseline.html"
    build_baseline_html(
        report_data={
            "meta": meta,
            "cards": cards,
            "metrics": metrics,
            "figures": figs,
            "phase3_text": phase3_text,
            "misclassified": df_miss,
        },
        output_path=baseline_html,
    )

    logger.info("=" * 60)
    logger.info(f"Report complete -> {baseline_html}")
    logger.info("=" * 60)

    print("\n" + phase3_text)
    print(f"\nReport saved: {baseline_html}")

    if args.open_browser:
        import webbrowser

        webbrowser.open(baseline_html.resolve().as_uri())


if __name__ == "__main__":
    main()
